---
title: "Dusti Assumption Checking 3-8-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

run packages
```{r}
library(lme4)
library(tidyverse)
library(mitml)
library(mice)

```

load data 
```{r}

load("~/GitHub/RESEV-553-Group-Project/df_imp3-8.rda")

df<- df_imp

df_mitml<- mids2mitml.list(df)

# df_comp <- complete(df) #use this line if you're working with imputed data



View(df_mitml[[2]])


```

list terms in df
```{r}

#list terms in the df
ls(df_mitml[[2]])

```

fix variables with spaces (R doesn't like spaces in things)
```{r}
# df<- df %>% 
#   rename(Income_cont = "Income_cont",
#          Educ = "EDUC")

#ls(df_comp)
```

run model
```{r}

#Not MI version
#mod_1<- lm(EDUC ~ 1 + Gender + Race, df)

#MI version
mod_1_mi <- with(df_comp, lm(EDUC_cont ~ 1 + Gender + Region))

```

```{r}
#not imputed
# plot(mod_1)


#imputed 
plot(mod_1_mi[[2]])

summary(mod_1_mi)

```

Make HLM 
```{r}
#see what categories exist
unique(df_comp$Region)

#turn the categories into numbers
df_mitml<- df_mitml %>% 
  mutate(Region_hlm = ifelse (Region == "Midwest", 1,
                              ifelse (Region == "South", 2,
                                      ifelse (Region == "West", 3, 
                                              ifelse (Region == "Northeast", 4, 0)))))


#run model

mod_1_hlm <- lm(EDUC_cont ~ 1 + Gender + Race + (1|Region_hlm))

summary(mod_1_hlm)
```
