---
title: "Census"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```




Open and rename data
```{r}
working_on_Friday_1_ <- read_csv("Census/working on Friday (1).csv")
df <- working_on_Friday_1_
```

Cut out extra variables and rename columns 
```{r}
#ls(df) can show us the variables
#select(var1, var2)
#rename(new name=old name)
df_small <- df %>%
  select(A_HGA, A_SEX, AGE1, PRDTRACE, WSAL_VAL) %>%
  rename(Educ = A_HGA,
         Gender = A_SEX,
         Age= AGE1,
         Race = PRDTRACE,
         Salary = WSAL_VAL)
```

clean data (age)
```{r}
#filter() decides what to keep
df_age <- df_small %>%
  filter(Age>=6,
         Age<=14)

```

Identify which races to include
```{r}
#Want at least 20
#table() will give us a count by race
table(df_age$Race)
df_race <- df_age %>%
  mutate(Race = ifelse(Race==1,"White",
                ifelse(Race==2,"Black",
                       ifelse(Race==3,"AIAN",
                              ifelse(Race==4,"Asian",
                                     ifelse(Race==5, "HP",
                                            ifelse(Race==6,"White-Black",
                                                   ifelse(Race==7,"White-AIAN",
                                                   ifelse(Race==8,"White-Asian","Other_Race")))))))))
```

Clean for gender
```{r}
#Same ideas as race
df_gender <- df_race %>%
  mutate(Gender = ifelse(Gender==1,"Men", "Women"))
```

Clean for education
```{r}
#mutate(ifelse()) with | (or) statements 
df_educ <- df_gender %>%
  mutate(Educ=ifelse(Educ<=38,"No_HS",
                     ifelse(Educ==39 | Educ==40,"HS",
                            ifelse(Educ==41 | Educ==42,"AA",
                                   ifelse(Educ==43,"BA",
                                          ifelse(Educ==44 | Educ==45,"MA",
                                                 ifelse(Educ==46,"PhD","Other_Educ")))))))
```

Save this new dataframe for later use
```{r}
df <- df_educ
write_rds(df, "cleaned_data.rds")
```


Descriptive statistics
```{r}
#group_by() %>% summarize()
#write.csv(desc_stat,'desc_stat.csv')
desc_stat <- df_educ %>% group_by(Race,Gender,Educ) %>%
  summarize(N=n(),
            mean=mean(Salary, na.rm=TRUE),
            SD=sd(Salary, na.rm=TRUE))

write.csv(desc_stat, "desc_stat.csv")
```

Plot descriptive
```{r}
#ggplot(data, aes(x= , y=, color =)) +
# geom_boxplot()
df_educ$Educ <- factor(df_educ$Educ,levels = c("No_HS", "HS", "AA", "BA", "MA", "PhD"))

ggplot(df_educ, aes(x=Race, y=Salary, color = Educ)) +
  geom_boxplot() +
  scale_y_continuous(trans='log2', limits=c(1000,2000000)) #+
  #facet_wrap(~Educ)

ggsave("myplot.png", width=8, height =3)
#  scale_y_continuous(trans='log2', limits=c(1000,2000000))
# save this for after first plot df$Educ <- factor(df$Educ,levels = c("No_HS", "HS", "AA", "BA", "MA", "PhD"))

# +facet_wrap(~race)
  #facet_wrap(~Educ)
#facet_wrap(~Gender)
#ggsave("myplot.png", width=8, height=3)
```





