---
title: "Dusti Data Cleaning 3-1-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Open and rename Data

```{r}
library(haven)
prgusap1_puf <- read_sas("prgusap1_puf.sas7bdat", 
    NULL)
View(prgusap1_puf)
df <- prgusap1_puf
```
Cut out Extra variables and rename columns
```{r}

#select(RACETHN_5CAT, REGION_US, EDCAT8, J_Q09USX, A_N01_T)
#rename(Race5=RACETHN_5CAT, Region=REGION_US, EDU8=EDCAT8, Income=J_Q09USX, Gender = A_N01_T)

df_small <- df%>%
  select(RACETHN_5CAT, REGION_US, EDCAT8, J_Q09USX, A_N01_T) %>%
  rename(Race=RACETHN_5CAT, Region=REGION_US, EDUC=EDCAT8, Income=J_Q09USX,
         Gender= A_N01_T)

```

Change name of Race Variables
```{r}
df <- df_small %>%
  mutate(Race = ifelse(Race==1, "Hispanic",
                       ifelse(Race==2, "White",
                              ifelse(Race==3, "Black",
                                     ifelse(Race==4, "Asian/Pacific Islander",
                                            ifelse(Race==6, "Other", "Not Stated" ))))))
                                                   
```
Change name of Region Variables
```{r}
df <- df %>%
  mutate(Region = ifelse(Region==1, "Northeast",
                         ifelse(Region==2, "Midwest",
                                ifelse(Region==3, "South",
                                       ifelse(Region==4, "West","Other")))))

```
Change name of Education Variables
```{r}
df <- df %>%
  mutate(EDUC = ifelse(EDUC==1 | EDUC==2, "Primary",
                       ifelse(EDUC==3 | EDUC==4, "Secondary",
                              ifelse(EDUC==6, "Bachelors",
                                     ifelse(EDUC==7, "Masters",
                                            ifelse(EDUC==5 | EDUC==8, "Professional", "Other"))))))
                                                   
```

make education variable continuous 
```{r}

df<- df %>%
  mutate(EDUC_cont = ifelse(EDUC== "Primary", 1,
                         ifelse(EDUC== "Secondary", 2,
                                ifelse(EDUC== "Bachelors", 3,
                                       ifelse(EDUC== "Masters", 4,
                                              ifelse(EDUC== "Professional", 5,0))))))
                                                     
     EDUC_cont = as.numeric(EDUC_cont)
         Race = as.factor(Race)
         Region = as.factor(Region)
         Gender = as.factor(Gender)
         EDUC = as.factor(EDUC)
         Income_cont = as.numeric(Income_cont)
 
```


change name of gender variable
```{r}
df <- df %>%
  mutate(Gender = ifelse(Gender==1, "Male",
                       ifelse(Gender==2, "Female", "Other")))
```

Change income variable 1st time
```{r}
df <- df %>%
  mutate(Income = ifelse(Income== 1 | Income== 2, "1-19,999",
                         ifelse(Income== 3 | Income== 4, "20,000-39,999",
                                ifelse(Income== 5 | Income== 6, "40,000-59,999",
                                       ifelse(Income== 7, "60,000-74,999",
                                              ifelse(Income== 8, "75,000-99,999",
                                                     ifelse(Income== 9, "100,000-149,999",
                                                            ifelse(Income== 10, "150,000 +", "Other" ))))))))
                                                                   #ifelse(Income== 11 | Income== is.na(NA), "Not Stated", "Other Income"))))))))) 
```


change name of income and make it continuous
```{r}
df<- df %>%
  mutate(Income_cont = ifelse(Income=="Not Stated",NA,
                         ifelse(Income=="1-19,999",1,
                                ifelse(Income=="20,000-39,999",2,
                                       ifelse(Income=="40,000-59,999",3,
                                              ifelse(Income=="60,000-74,999",4,
                                                     ifelse(Income=="75,000-99,999",5,
                                                            ifelse(Income=="100,000-149,999",6,0))))))),
    Income_cont = as.numeric(Income_cont),
         Race = as.factor(Race),
         Region = as.factor(Region),
         Income = as.factor(Income),
         EDUC = as.factor(EDUC)         )
  

summary(df)
```
save
```{r}

write.csv(df, "dfclean3-8.csv")
```


