---
title: "In Class Example - Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
Open and rename Data
```{r}
library(haven)
prgusap1_puf <- read_sas("prgusap1_puf.sas7bdat", 
    NULL)
View(prgusap1_puf)
df <- prgusap1_puf
```
Cut out Extra variables and rename columns
```{r}
#select(RACETHN_5CAT, REGION_US, EDCAT8, J_Q09USX)
#rename(Race5=RACETHN_5CAT, Region=REGION_US, EDU8=EDCAT8, Income=J_Q09USX)
df_small <- df%>%
  select(RACETHN_5CAT, REGION_US, EDCAT8, J_Q09USX) %>%
  rename(Race=RACETHN_5CAT, Region=REGION_US, EDUC=EDCAT8, Income=J_Q09USX)

```

Change name of Race Variables
```{r}
df_Race <- df_small %>%
  mutate(Race = ifelse(Race==1, "Hispanic",
                       ifelse(Race==2, "White",
                              ifelse(Race==3, "Black",
                                     ifelse(Race==4, "Asian/Pacific Islander",
                                            ifelse(Race==6, "Other",
                                                   ifelse(Race==NA, "Not Stated")))))))
```
Change name of Region Variables
```{r}
df_Region_Race <- df_Race %>%
  mutate(Region = ifelse(Region== 1, "Northeast",
                         ifelse(Region== 2, "Midwest",
                                ifelse(Region== 3, "South",
                                       ifelse(Region== 4, "West", "Other Region")))))
```
Change name of Education Variables
```{r}
df_Ed_Reg_Race <- df_Region_Race %>%
  mutate(EDUC = ifelse(EDUC==1 | EDUC==2, "Primary",
                       ifelse(EDUC==3 | EDUC==4, "Secondary",
                              ifelse(EDUC==6, "Bachelors",
                                     ifelse(EDUC==7, "Masters",
                                            ifelse(EDUC==5 | EDUC==8, "Professional",
                                                   ifelse(EDUC==NA, "Not Stated")))))))
```
Change name of Income Variable
```{r}
df_ALL <- df_Ed_Reg_Race %>%
  mutate(Income = ifelse(Income== 1 | Income==2, "1-19,999",
                         ifelse(Income==3 | Income== 4, "20,000-39,999",
                                ifelse(Income== 5 | Income==6, "40,000-59,999",
                                       ifelse(Income==7, "60,000-74,999",
                                              ifelse(Income==8, "75,000-99,999",
                                                     ifelse(Income==10, "100,000-149,999",
                                                            ifelse(Income== 11 | Income==NA, "Not Stated", "Other Income")))))))) 
```


Descriptive Statistics
```{r}
#group_by() %>^ summarize()
#write.csv(desc_stat, 'desc_stat.csv')
desc_stat <
```

