---
title: "Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Everyone needs these
library(tidyverse)
library(lme4)

#Those with imputed data might need
library(MuMIn)
library(mitml)
library(mice)
library(miceadds)
```

Clear working memory
```{r}
#This is the same as hitting the broom icon
#rm(list = ls(all.names = TRUE))
```

Load the data, make complete dataset, and mitml
```{r}
load("~/RESEV_553/Survey of adult skills/df_imp.rda")
df <- complete(df_imp)
df_mitml <- mids2mitml.list(df_imp)
```


Run models
```{r}
mod_1 <- lm(Income_cont ~ 1, df)
mod_2 <- lm(Income_cont ~ 1 + Race, df)
mod_3 <- lm(Income_cont ~ 1 + Race + Region, df)
mod_4 <- lm(Income_cont ~ 1 + Race*Region, df)
  
mod <- with(df_mitml, lm(Income_cont ~ 1 +Race))
```

Check output
```{r}
summary(mod_1)
summary(mod_2)
summary(mod_3)
summary(mod_4)

testEstimates(mod, extra.pars=TRUE)
```

Save output
```{r}
#regular saving
save(mod_1, file="mod_1.rda")
output <- summary(mod_1)
estimates <- output[["coefficients"]]
write.csv(estimates, file="estimates.csv")

#MI saving
save(mod,file="mod.rda")
output_imp <- testEstimates(mod, extra.pars=TRUE)
estimates <- output_imp[["estimates"]]
write.csv(estimates, file="estimates.csv")
```

